/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveTaskButton: typeof import('./src/components/ActiveTaskButton.vue')['default']
    ActivityChart: typeof import('./src/components/ActivityChart.vue')['default']
    ActivityModal: typeof import('./src/components/ActivityModal.vue')['default']
    ActivityView: typeof import('./src/components/ActivityView.vue')['default']
    App: typeof import('./src/components/App.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownForm']
    BDropdownHeader: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownHeader']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItemButton']
    BDropdownText: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownText']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    CompleteStatus: typeof import('./src/components/CompleteStatus.vue')['default']
    DailyActivitySummary: typeof import('./src/components/DailyActivitySummary.vue')['default']
    IntervalDropdownForm: typeof import('./src/components/IntervalDropdownForm.vue')['default']
    Log: typeof import('./src/components/Log.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NavbarArchiveDropdown: typeof import('./src/components/navbar/NavbarArchiveDropdown.vue')['default']
    NavbarOptionsDropdown: typeof import('./src/components/navbar/NavbarOptionsDropdown.vue')['default']
    NavbarTagsDropdown: typeof import('./src/components/navbar/NavbarTagsDropdown.vue')['default']
    SelectedTask: typeof import('./src/components/SelectedTask.vue')['default']
    TagButton: typeof import('./src/components/TagButton.vue')['default']
    TagEditMenu: typeof import('./src/components/TagEditMenu.vue')['default']
    TagInput: typeof import('./src/components/TagInput.vue')['default']
    TagSettingsButton: typeof import('./src/components/TagSettingsButton.vue')['default']
    Task: typeof import('./src/components/Task.vue')['default']
    TaskFilterDropdown: typeof import('./src/components/TaskFilterDropdown.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TaskMenu: typeof import('./src/components/TaskMenu.vue')['default']
    TaskTagList: typeof import('./src/components/TaskTagList.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TimerDial: typeof import('./src/components/TimerDial.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
